name: Publish

permissions:
  contents: write
  
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: heimdall
            asset_name: heimdall-linux-amd64
          - os: macos-latest
            artifact_name: heimdall
            asset_name: heimdall-macos-amd64
          - os: windows-latest
            artifact_name: heimdall-win.exe
            asset_name: heimdall-windows-amd64

    steps:
    - uses: actions/checkout@v2

    - name: Build Binaries
      run:  |
        cargo clean
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          echo "Building on Windows"
          powershell -Command "Set-Item -Path Env:RUSTFLAGS -Value '-C codegen-units=1'; Set-Item -Path Env:CARGO_PROFILE_RELEASE_LTO -Value 'true'; cargo build --release"
        else
          echo "Building on Unix-based OS"
          RUSTFLAGS="-C codegen-units=1" CARGO_PROFILE_RELEASE_LTO=true cargo build --release
        fi
      shell: bash


