name: Publish

permissions:
  contents: write
  
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: heimdall
            asset_name: heimdall-linux-amd64
          - os: macos-latest
            artifact_name: heimdall
            asset_name: heimdall-macos-amd64
          - os: windows-latest
            artifact_name: heimdall.exe
            asset_name: heimdall-windows-amd64

    steps:
    - uses: actions/checkout@v2

    - name: Build Binaries
      run:  |
        cargo clean
        RUSTFLAGS="-C codegen-units=1" CARGO_PROFILE_RELEASE_LTO=true cargo build --release


